spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  redis:
    host: localhost
    port: 16379

logging:
  level:
    com.finaya.pixwallet: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.SQL: DEBUG